### PR TITLE
Fixed text to be more inline with the OG game

### PR DESCRIPTION
**Pull request by spjoes**
Since the current main menu is whats in teh OG game and highlighted on the first option, I made the text what it is supposed to be

### CODE REVIEW

**Comment by spjoes** [comment]
I also just fixed the way to fast animations

**Comment by spjoes** [comment]
Just added the Colorize lib and added text to the buttons in the title.lua

**Comment by spjoes** [comment]
Just added music to the title screen in .flac format (no compression). It auto-loops so change that if you would like

**Comment by spjoes** [comment]
Tried to add eCDP font and ecdp logo

**Review by TeamPopplio — APPROVED** [review]
Seems like some things aren't where they should be (colorize -> lib, audio inside of the blank audio lua file, fonts should be in gfx, etc) but I'll go ahead and merge this.

**Pull request merged**
